
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ANHIJEET
 */
public class book_request extends javax.swing.JInternalFrame {

    /**
     * Creates new form book_request
     */
    public book_request() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cmb_purpose = new javax.swing.JComboBox<>();
        txtbook_name = new javax.swing.JTextField();
        txtbook_author = new javax.swing.JTextField();
        txtbook_publisher = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtbook_details = new javax.swing.JTextArea();
        btn_sumit = new javax.swing.JButton();
        btn_clear = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtstudent_id = new javax.swing.JTextField();
        txts_name = new javax.swing.JTextField();
        cmb_course = new javax.swing.JComboBox<>();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Black", 3, 18)); // NOI18N
        jLabel1.setText("BOOK REQUEST");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, 180, -1));

        jLabel2.setText("BOOK Name: ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        jLabel3.setText("BOOK Author :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        jLabel4.setText("BOOK Publisher :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        jLabel5.setText("FOR WHAT PURPOSE YOU WANT THIS BOOK :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, -1));

        cmb_purpose.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Referance", "Group project", "Whole Class", "For Study" }));
        jPanel1.add(cmb_purpose, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 300, 110, -1));

        txtbook_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbook_nameActionPerformed(evt);
            }
        });
        jPanel1.add(txtbook_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 122, 180, 30));
        jPanel1.add(txtbook_author, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 182, 180, 30));
        jPanel1.add(txtbook_publisher, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 242, 180, 30));

        jLabel6.setText("BOOK Details:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, -1, -1));

        txtbook_details.setColumns(20);
        txtbook_details.setRows(5);
        jScrollPane1.setViewportView(txtbook_details);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 350, 230, -1));

        btn_sumit.setText("SUBMIT");
        btn_sumit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sumitActionPerformed(evt);
            }
        });
        jPanel1.add(btn_sumit, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 500, -1, -1));

        btn_clear.setText("CLEAR");
        btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearActionPerformed(evt);
            }
        });
        jPanel1.add(btn_clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 500, -1, -1));

        jLabel7.setText("Student ID:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 120, -1, -1));

        jLabel8.setText("Student Name: ");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 180, -1, -1));

        jLabel9.setText("Student Branch :");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 230, -1, -1));

        txtstudent_id.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtstudent_idFocusLost(evt);
            }
        });
        jPanel1.add(txtstudent_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 112, 170, 30));
        jPanel1.add(txts_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 162, 170, 30));

        cmb_course.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CSE", "ME", "ELE", "CIVIL" }));
        cmb_course.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_courseActionPerformed(evt);
            }
        });
        jPanel1.add(cmb_course, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 230, 110, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtbook_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbook_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbook_nameActionPerformed

    private void cmb_courseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_courseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_courseActionPerformed

    private void txtstudent_idFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtstudent_idFocusLost
        // TODO add your handling code here:
         try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/librarydatabase", "root", "");
            String sql="select * from studen_reg where id= '"+txtstudent_id.getText()+"'";
            PreparedStatement pst=con.prepareStatement(sql);
            ResultSet rs=pst.executeQuery();
            int status=0;
            
            while(rs.next()){
                status +=1;
                txts_name.setText(rs.getString("name"));
                cmb_course.setSelectedItem(rs.getString("course"));
            }}
          catch(Exception ex){
          JOptionPane.showMessageDialog(null, ex.getMessage());}
    
    }//GEN-LAST:event_txtstudent_idFocusLost

    private void btn_sumitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sumitActionPerformed
        // TODO add your handling code here:
        
            try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/librarydatabase","root","");
            String sql2="select * from book_entry where name='"+txtbook_name.getText()+"' and author='"+txtbook_author.getText() +"' ";
            PreparedStatement pst1= con.prepareStatement(sql2);
             ResultSet rs=pst1.executeQuery();
            int status=0;
            
            if(rs.next()){
                status +=1;
                JOptionPane.showMessageDialog(null, "THIS BOOK IS ALREADY AVAILABLE IN LIBRARY");
            }else{
           
            String sql="insert into book_req(bname,bauthor,bpublisher,sid,sname,scourse,bpurpose,bdetails) values('" +txtbook_name.getText()+"','" +txtbook_author.getText()+"','" +txtbook_publisher.getText()+"','" +txtstudent_id.getText()+"','" +txts_name.getText()+"','" +cmb_course.getSelectedItem()+"','"+cmb_purpose.getSelectedItem()+"','" +txtbook_details.getText()+"')  ";
            PreparedStatement pst= con.prepareStatement(sql);
            
            int i=pst.executeUpdate();
            
            
					if(i>0) {
						JOptionPane.showMessageDialog(null, "record save sucess");
				}
					con.close();
					pst.close();
        
        }}
        catch(Exception e){
            JOptionPane.showMessageDialog(null, " "+e.getMessage());
        }

        
        
    }//GEN-LAST:event_btn_sumitActionPerformed

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
        // TODO add your handling code here:
        txtbook_name.setText(" ");
        txtbook_author.setText(" ");
        txtbook_publisher.setText(" ");
        txts_name.setText(" ");
        txtstudent_id.setText(" ");
        cmb_course.setSelectedItem(null);
        cmb_purpose.setSelectedItem(null);
        txtbook_details.setText(" ");
    }//GEN-LAST:event_btn_clearActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_clear;
    private javax.swing.JButton btn_sumit;
    private javax.swing.JComboBox<String> cmb_course;
    private javax.swing.JComboBox<String> cmb_purpose;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtbook_author;
    private javax.swing.JTextArea txtbook_details;
    private javax.swing.JTextField txtbook_name;
    private javax.swing.JTextField txtbook_publisher;
    private javax.swing.JTextField txts_name;
    private javax.swing.JTextField txtstudent_id;
    // End of variables declaration//GEN-END:variables
}
