/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ANHIJEET
 */
import java.awt.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
public class book_entery extends javax.swing.JInternalFrame {

    /**
     * Creates new form book_entery
     */
    public book_entery() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtbook_id = new javax.swing.JTextField();
        txtbook_name = new javax.swing.JTextField();
        txtbook_author = new javax.swing.JTextField();
        txtbook_publisher = new javax.swing.JTextField();
        txtbook_stock = new javax.swing.JTextField();
        txtbook_possition = new javax.swing.JTextField();
        btnsearch = new javax.swing.JButton();
        btnsave = new javax.swing.JButton();
        btnupdate = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        btnclear = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_view = new javax.swing.JTable();
        btn_allbooksdetails = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("BOOK ENTRY");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("BOOK ENTRY ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 30, -1, -1));

        jLabel2.setText("BOOK ID :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 108, -1, -1));

        jLabel3.setText("BOOK NAME :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 174, -1, -1));

        jLabel4.setText("BOOK AUTHOR :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 244, -1, -1));

        jLabel5.setText("BOOK PUBLISHER :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 319, -1, -1));

        jLabel6.setText("STOCK AVAILABLE :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 384, -1, -1));

        jLabel7.setText("BOOK POSSITION :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 455, -1, -1));
        jPanel1.add(txtbook_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 100, 205, 33));

        txtbook_name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtbook_nameKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtbook_nameKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtbook_nameKeyTyped(evt);
            }
        });
        jPanel1.add(txtbook_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 167, 205, 30));
        jPanel1.add(txtbook_author, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 237, 205, 31));
        jPanel1.add(txtbook_publisher, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 311, 205, 32));
        jPanel1.add(txtbook_stock, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 366, 205, 34));
        jPanel1.add(txtbook_possition, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 446, 205, 35));

        btnsearch.setText("SEARCH");
        btnsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsearchActionPerformed(evt);
            }
        });
        jPanel1.add(btnsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 521, -1, -1));

        btnsave.setText("SAVE");
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });
        jPanel1.add(btnsave, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 521, -1, -1));

        btnupdate.setText("UPDATE");
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });
        jPanel1.add(btnupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(243, 521, -1, -1));

        btndelete.setText("DELETE");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });
        jPanel1.add(btndelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 521, -1, -1));

        btnclear.setText("CLEAR");
        btnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearActionPerformed(evt);
            }
        });
        jPanel1.add(btnclear, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 520, -1, -1));

        table_view.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(table_view);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 559, 853, 250));

        btn_allbooksdetails.setText("ALL BOOKS ");
        btn_allbooksdetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_allbooksdetailsActionPerformed(evt);
            }
        });
        jPanel1.add(btn_allbooksdetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 520, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 840));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearActionPerformed
        // TODO add your handling code here:
        txtbook_author.setText(" ");
        txtbook_name.setText(" ");
        txtbook_possition.setText(" ");
        txtbook_publisher.setText(" ");
        txtbook_stock.setText(" ");
        
        
    }//GEN-LAST:event_btnclearActionPerformed

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
        // TODO add your handling code here:
        
        
         try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/librarydatabase","root","");
            String sql="insert into book_entry(name,author,publisher,stock,possition,availablestock) values('" +txtbook_name.getText()+"','" +txtbook_author.getText()+"','" +txtbook_publisher.getText()+"','"+txtbook_stock.getText()+"','" +txtbook_possition.getText()+"','"+txtbook_stock.getText()+"')  ";
            PreparedStatement pst= con.prepareStatement(sql);
            int i=pst.executeUpdate();
					if(i>0) {
						JOptionPane.showMessageDialog(null, "record save sucess");
				}
					con.close();
					pst.close();
        
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, " "+e.getMessage());
        }

    }//GEN-LAST:event_btnsaveActionPerformed

    private void txtbook_nameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbook_nameKeyPressed
        // TODO add your handling code here:
      String n=  txtbook_name.getText();
       try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/librarydatabase", "root", "");
            String sql="select * from book_entry where name LIKE '"+n+"%' ";
            PreparedStatement pst=con.prepareStatement(sql);
            ResultSet rs=pst.executeQuery();
            table_view.setModel(DbUtils.resultSetToTableModel(rs));
          
      }catch(Exception ex){
          JOptionPane.showMessageDialog(null, ex.getMessage());
      }
     
        
        
    }//GEN-LAST:event_txtbook_nameKeyPressed

    private void txtbook_nameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbook_nameKeyReleased
        // TODO add your handling code here:txt
        txtbook_name.getText();
    }//GEN-LAST:event_txtbook_nameKeyReleased

    private void txtbook_nameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbook_nameKeyTyped
        // TODO add your handling code here:
        txtbook_name.getText();
    }//GEN-LAST:event_txtbook_nameKeyTyped

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        // TODO add your handling code here:
         try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/librarydatabase", "root", "");
            String sql="delete from book_entry where name='"+txtbook_id.getText()+"'";
            PreparedStatement pst=con.prepareStatement(sql);
            int i=pst.executeUpdate();
            if(i>0){
                JOptionPane.showMessageDialog(null, "Sucessfully Deleted");
            }
        }catch(Exception e1){
            JOptionPane.showMessageDialog(null, e1);
        }
    }//GEN-LAST:event_btndeleteActionPerformed

    private void btnsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsearchActionPerformed
        // TODO add your handling code here:
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/librarydatabase", "root", "");
            String sql="select * from book_entry where book_id= '"+txtbook_id.getText()+"'";
            PreparedStatement pst=con.prepareStatement(sql);
            ResultSet rs=pst.executeQuery();
            int status=0;
            
            while(rs.next()){
                status +=1;
                txtbook_name.setText(rs.getString("name"));
                txtbook_author.setText(rs.getString("author"));
                txtbook_publisher.setText(rs.getString("publisher"));
                txtbook_stock.setText(rs.getString("stock"));
                txtbook_possition.setText(rs.getString("possition"));
            }
        }catch(Exception ex){
        JOptionPane.showMessageDialog(null, ex.getMessage());}
    }//GEN-LAST:event_btnsearchActionPerformed

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        // TODO add your handling code here:
         try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/librarydatabase", "root", "");
            String sql="update book_entry set name='"+txtbook_name.getText()+"', author='"+txtbook_author.getText()+"',publisher='"+txtbook_publisher.getText()+"', stock='"+txtbook_stock.getText()+"', possition= '"+txtbook_possition.getText()+"' where id='"+ txtbook_id+"'";
            PreparedStatement pst=con.prepareStatement(sql);
            int i=pst.executeUpdate();
            if(i>0){
                 JOptionPane.showMessageDialog(null,"Record Update");
            }
             
        }catch(Exception e1){
            JOptionPane.showMessageDialog(null, e1.getMessage());
        }
    }//GEN-LAST:event_btnupdateActionPerformed

    private void btn_allbooksdetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_allbooksdetailsActionPerformed
        // TODO add your handling code here:
         try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/librarydatabase", "root", "");
            String sql="select * from book_entry";
            PreparedStatement pst=con.prepareStatement(sql);
            ResultSet rs=pst.executeQuery();
            table_view.setModel(DbUtils.resultSetToTableModel(rs));
          
      }catch(Exception ex){
          JOptionPane.showMessageDialog(null, ex.getMessage());
      }
        
     
    }//GEN-LAST:event_btn_allbooksdetailsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_allbooksdetails;
    private javax.swing.JButton btnclear;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnsave;
    private javax.swing.JButton btnsearch;
    private javax.swing.JButton btnupdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table_view;
    private javax.swing.JTextField txtbook_author;
    private javax.swing.JTextField txtbook_id;
    private javax.swing.JTextField txtbook_name;
    private javax.swing.JTextField txtbook_possition;
    private javax.swing.JTextField txtbook_publisher;
    private javax.swing.JTextField txtbook_stock;
    // End of variables declaration//GEN-END:variables
}
