
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Properties;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ANHIJEET
 */
public class book_fine extends javax.swing.JInternalFrame {

    /**
     * Creates new form book_fine
     */
    public book_fine() {
        
        initComponents();
        btn_print.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_fine = new javax.swing.JTextField();
        btn_submit = new javax.swing.JButton();
        btn_clear = new javax.swing.JButton();
        btn_print = new javax.swing.JButton();
        txts_id = new javax.swing.JTextField();
        txts_name = new javax.swing.JTextField();
        cmb_course = new javax.swing.JComboBox<>();
        txtb_id = new javax.swing.JTextField();
        txtb_name = new javax.swing.JTextField();
        txtb_author = new javax.swing.JTextField();
        current_date = new com.toedter.calendar.JDateChooser();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Black", 3, 18)); // NOI18N
        jLabel1.setText("BOOK FINE");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, 130, -1));

        jLabel2.setText("STUDENT ID:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        jLabel3.setText("S_NAME: ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        jLabel4.setText("BRANCH :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        jLabel5.setText("BOOK ID:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 90, -1, -1));

        jLabel6.setText("BOOK_NAME:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 140, -1, -1));

        jLabel7.setText("BOOK AUHTOR :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 190, -1, -1));

        jLabel8.setText("DATE :");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 240, -1, -1));

        jLabel9.setText("TOTAL FINE :");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, -1, -1));

        txt_fine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_fineActionPerformed(evt);
            }
        });
        jPanel1.add(txt_fine, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 330, 200, -1));

        btn_submit.setText("submit");
        btn_submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_submitActionPerformed(evt);
            }
        });
        jPanel1.add(btn_submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, -1, -1));

        btn_clear.setText("clear");
        btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearActionPerformed(evt);
            }
        });
        jPanel1.add(btn_clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 420, -1, -1));

        btn_print.setText("PRINT");
        jPanel1.add(btn_print, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 420, -1, -1));

        txts_id.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txts_idFocusLost(evt);
            }
        });
        jPanel1.add(txts_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 140, -1));
        jPanel1.add(txts_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 140, -1));

        cmb_course.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CSE", "ME", "ELE", "CIVIL" }));
        jPanel1.add(cmb_course, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 140, -1));

        txtb_id.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtb_idFocusLost(evt);
            }
        });
        jPanel1.add(txtb_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 90, 140, -1));
        jPanel1.add(txtb_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 140, 140, -1));
        jPanel1.add(txtb_author, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 190, 140, -1));
        jPanel1.add(current_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 230, 140, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 640, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_fineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_fineActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_fineActionPerformed

    private void txts_idFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txts_idFocusLost
        // TODO add your handling code here:
         try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/librarydatabase", "root", "");
            String sql="select * from studen_reg where id= '"+txts_id.getText()+"'";
            PreparedStatement pst=con.prepareStatement(sql);
            ResultSet rs=pst.executeQuery();
            int status=0;
            
            while(rs.next()){
                status +=1;
                txts_name.setText(rs.getString("name"));
                cmb_course.setSelectedItem(rs.getString("course"));
            }}
          catch(Exception ex){
          JOptionPane.showMessageDialog(null, ex.getMessage());}
    }//GEN-LAST:event_txts_idFocusLost

    private void txtb_idFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtb_idFocusLost
        // TODO add your handling code here:
   try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/librarydatabase", "root", "");
            String sql="select * from book_issue where bid= '"+txtb_id.getText()+"' and sid='"+txts_id.getText()+"' and status='"+1+"'";
            PreparedStatement pst=con.prepareStatement(sql);
            ResultSet rs=pst.executeQuery();
            int status=0;
            
            while(rs.next()){
                status +=1;
                txtb_author.setText(rs.getString("author"));
                txtb_name.setText(rs.getString("name"));
                
            }
            DateTimeFormatter dtf = DateTimeFormatter.ofPattern("dd/MM/yyyy");  
   LocalDateTime now = LocalDateTime.now();  
   String currentdate=dtf.format(now);
   try {
           
            java.util.Date date= new SimpleDateFormat("dd/MM/yyyy").parse(currentdate);
            current_date.setDate(date);current_date.disable();
            
             
        } catch (Exception ex) {
           JOptionPane.showMessageDialog(null, ex);
        }
            pst.close();
            con.close();
         }
          catch(Exception ex){
          JOptionPane.showMessageDialog(null, ex.getMessage());}
        
              
    }//GEN-LAST:event_txtb_idFocusLost

    private void btn_submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_submitActionPerformed
        // TODO add your handling code here:
        try{ java.util.Date date = current_date.getDate();
        DateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");
        String dateofbirth = formatter.format(date);
             Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/librarydatabase","root","");
             String sqlq="update book_issue set status=0 where sid='"+txts_id.getText()+"' and status=1";
             PreparedStatement pst= con.prepareStatement(sqlq);
             pst.executeUpdate();
             
            sqlq="update book_fine set status=0 where sid='"+txts_id.getText()+"' and status=1";
            PreparedStatement pst1= con.prepareStatement(sqlq);
            
            int i=pst.executeUpdate();
            if(i>0) {
		JOptionPane.showMessageDialog(null, "student id: "+txts_id.getText()+" paid "+txt_fine);
		}
                                   
          Properties props = new Properties();    
          props.put("mail.smtp.host", "smtp.gmail.com");    
          props.put("mail.smtp.socketFactory.port", "465");    
          props.put("mail.smtp.socketFactory.class",    
                    "javax.net.ssl.SSLSocketFactory");    
          props.put("mail.smtp.auth", "true");    
          props.put("mail.smtp.port", "587");    
          //get Session   
          Session session = Session.getInstance(props, 
                  new javax.mail.Authenticator() {    
           @Override
           protected PasswordAuthentication getPasswordAuthentication() {    
           return new PasswordAuthentication("rowlandrowland554@gmail.com","rohan@123");  
           }    
          });    
          //compose message 
           sqlq =" select mail from studen_reg where id='"+ txts_id.getText()+"'";
            PreparedStatement pst4=con.prepareStatement(sqlq);
            ResultSet rs4=pst4.executeQuery();
            String subjeet="returned book",mess=" you have returned this book id: '"+txtb_id.getText()+"' and name :'"+txtb_name.getText()+"'  return date: '"+ current_date.getDate()+"'",smail = null;
            while(rs4.next()){
                 smail = rs4.getString(1);
            }
          
          try {    
           MimeMessage message = new MimeMessage(session);    
           message.addRecipient(Message.RecipientType.TO,new InternetAddress(smail));    
           message.setSubject(subjeet);    
           message.setText(mess);    
           //send message  
           Transport.send(message);    
           System.out.println("message sent successfully");    
          }catch (MessagingException e) {throw new RuntimeException(e);}
	
        }catch(Exception ex){ JOptionPane.showMessageDialog(null, ex.getMessage());
        }
        
        
    }//GEN-LAST:event_btn_submitActionPerformed

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
        // TODO add your handling code here:
        txt_fine.setText(" ");
        txtb_author.setText(" ");
        txtb_id.setText(" ");
        txtb_name.setText(" ");
        txts_id.setText(" ");
        txts_name.setText(" ");
    }//GEN-LAST:event_btn_clearActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_clear;
    private javax.swing.JButton btn_print;
    private javax.swing.JButton btn_submit;
    private javax.swing.JComboBox<String> cmb_course;
    private com.toedter.calendar.JDateChooser current_date;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txt_fine;
    private javax.swing.JTextField txtb_author;
    private javax.swing.JTextField txtb_id;
    private javax.swing.JTextField txtb_name;
    private javax.swing.JTextField txts_id;
    private javax.swing.JTextField txts_name;
    // End of variables declaration//GEN-END:variables
}
