
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ANHIJEET
 */
public class student_details extends javax.swing.JInternalFrame {
String gender,course,imagename;
    /**
     * Creates new form student_details
     */
    public student_details() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        date_chooser = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_id = new javax.swing.JTextField();
        txt_name = new javax.swing.JTextField();
        txt_mail = new javax.swing.JTextField();
        txt_pass = new javax.swing.JPasswordField();
        rd_male = new javax.swing.JRadioButton();
        rd_female = new javax.swing.JRadioButton();
        rd_other = new javax.swing.JRadioButton();
        cmbocourse = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_address = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        lblimg = new javax.swing.JLabel();
        btnsearch = new javax.swing.JButton();
        btnupdate = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        btnclear = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_view = new javax.swing.JTable();
        btn_allview = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel1.setText("STUDENT DETAILS");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, -1, -1));

        jLabel2.setText("ID :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jLabel3.setText("Name :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        jLabel4.setText("E-mail :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        jLabel5.setText("Password :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        jLabel6.setText("Dob :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));
        jPanel1.add(date_chooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 282, 180, 30));

        jLabel7.setText("Gender :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, -1, -1));

        jLabel8.setText("stream/course :");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, -1, -1));

        jLabel9.setText("Address :");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, -1, -1));
        jPanel1.add(txt_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 180, 30));
        jPanel1.add(txt_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 180, 30));
        jPanel1.add(txt_mail, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 172, 180, 30));
        jPanel1.add(txt_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 222, 180, 30));

        rd_male.setText("Male");
        jPanel1.add(rd_male, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 350, -1, -1));

        rd_female.setText("Female");
        jPanel1.add(rd_female, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 350, -1, -1));

        rd_other.setText("Other");
        jPanel1.add(rd_other, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 350, -1, -1));

        cmbocourse.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CSE", "ME", "ELE", "CIVIL" }));
        jPanel1.add(cmbocourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 420, 170, -1));

        txt_address.setColumns(20);
        txt_address.setRows(5);
        jScrollPane1.setViewportView(txt_address);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 480, 220, 150));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblimg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblimg, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 70, 170, 190));

        btnsearch.setText("SEARCH");
        btnsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsearchActionPerformed(evt);
            }
        });
        jPanel1.add(btnsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 730, -1, -1));

        btnupdate.setText("UPDATE");
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });
        jPanel1.add(btnupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 730, -1, -1));

        btndelete.setText("DELETE");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });
        jPanel1.add(btndelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 730, -1, -1));

        btnclear.setText("CLEAR");
        btnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearActionPerformed(evt);
            }
        });
        jPanel1.add(btnclear, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 730, -1, -1));

        table_view.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table_view.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_viewMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(table_view);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 780, 610, -1));

        btn_allview.setText("All details");
        btn_allview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_allviewActionPerformed(evt);
            }
        });
        jPanel1.add(btn_allview, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 730, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 636, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1058, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsearchActionPerformed
        // TODO add your handling code here:
          try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/librarydatabase", "root", "");
            String sql="select * from studen_reg where id= '"+txt_id.getText()+"'";
            PreparedStatement pst=con.prepareStatement(sql);
            ResultSet rs=pst.executeQuery();
            int status=0;
            
            while(rs.next()){
                status +=1;
                txt_name.setText(rs.getString("name"));
                txt_mail.setText(rs.getString("mail"));
                txt_pass.setText(rs.getString("password"));
                txt_address.setText(rs.getString("address"));
                String d = rs.getString("dob");
                java.util.Date date = new SimpleDateFormat("dd/MM/yyyy").parse(d);
                date_chooser.setDate(date);
                gender= rs.getString("gender");
                if(gender.equalsIgnoreCase("male")){
                rd_male.setSelected(true);
        rd_female.setSelected(false);
        rd_other.setSelected(false);
        
                }
                else if(gender.equalsIgnoreCase("female")){
                    rd_male.setSelected(false);
        rd_female.setSelected(true);
        rd_other.setSelected(false);
        
                }
                
                else{
                    rd_male.setSelected(false);
        rd_female.setSelected(false);
        rd_other.setSelected(true);
        
                }
                
                cmbocourse.setSelectedItem(rs.getString("course"));
               String img = rs.getString("imagename");
               lblimg.setIcon(new ImageIcon("G:\\internship\\images"+img));
               
                
                
            }
            
        }catch(Exception e1){
            JOptionPane.showMessageDialog(null, e1.getMessage());
        }
    }//GEN-LAST:event_btnsearchActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        // TODO add your handling code here:
         try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/student_batch7", "root", "");
            String sql="delete from studen_reg where name='"+txt_id.getText()+"'";
            PreparedStatement pst=con.prepareStatement(sql);
            int i=pst.executeUpdate();
            if(i>0){
                JOptionPane.showMessageDialog(null, "Sucessfully Deleted");
            }
        }catch(Exception e1){
            JOptionPane.showMessageDialog(null, e1);
        }
    }//GEN-LAST:event_btndeleteActionPerformed

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        // TODO add your handling code here:
        java.util.Date date = date_chooser.getDate();
        DateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");
        String dateofbirth = formatter.format(date);
         try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/librarydatabase", "root", "");
            String sql="update studen_reg set name='"+txt_name.getText()+"', mail='"+txt_mail.getText()+"', password='"+txt_pass.getText()+"', dob='"+dateofbirth+"',  gender='"+gender+"',course='"+cmbocourse.getSelectedItem()+"',address='"+txt_address.getText()+"',photo='"+imagename+"' where id='"+ txt_id+"'";
            PreparedStatement pst=con.prepareStatement(sql);
            int i=pst.executeUpdate();
            if(i>0){
                 JOptionPane.showMessageDialog(null,"Record Update");
            }
             
        }catch(Exception e1){
            JOptionPane.showMessageDialog(null, e1.getMessage());
        }
    }//GEN-LAST:event_btnupdateActionPerformed

    private void btnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearActionPerformed
        // TODO add your handling code here:
         rd_male.setSelected(false);
         rd_female.setSelected(false);
         rd_other.setSelected(false);
           txt_mail.setText(" ");
            txt_name.setText(" ");
            txt_pass.setText(null);
            cmbocourse.setSelectedItem(null);
            txt_address.setText(" ");
    
    }//GEN-LAST:event_btnclearActionPerformed

    private void btn_allviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_allviewActionPerformed
        // TODO add your handling code here:
      try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/librarydatabase", "root", "");
            String sql="select * from studen_reg";
            PreparedStatement pst=con.prepareStatement(sql);
            ResultSet rs=pst.executeQuery();
            table_view.setModel(DbUtils.resultSetToTableModel(rs));
          
      }catch(Exception ex){
          JOptionPane.showMessageDialog(null, ex.getMessage());
      }
        
        
        
        
        
       
       
    }//GEN-LAST:event_btn_allviewActionPerformed

    private void table_viewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_viewMouseClicked
        // TODO add your handling code here:
        TableModel tbl = table_view.getModel();
        int row = table_view.getSelectedRow();
        int columb = table_view.getSelectedColumn();
       int id = (int) table_view.getValueAt(row, 0);
       String name= (String) table_view.getValueAt(row, 1);
       String emial= (String) table_view.getValueAt(row, 2);
       String pass= (String) table_view.getValueAt(row, 3);
       String address= (String) table_view.getValueAt(row, 7);
       String g = (String) table_view.getValueAt(row, 5);
       
       if(g.equalsIgnoreCase("male")){
           rd_male.setSelected(true);
       }
       else if(g.equalsIgnoreCase("female")){
           rd_female.setSelected(true);
       }
       else{
           rd_other.setSelected(true);
       }
       String d = (String) table_view.getValueAt(row, 4);
          java.util.Date date1 = null;
    try {
        date1 = new SimpleDateFormat("dd/MM/yyyy").parse(d);
        date_chooser.setDate(date1);
    } catch (ParseException ex) {
        Logger.getLogger(student_details.class.getName()).log(Level.SEVERE, null, ex);
    }
                
       
       txt_id.setText(""+id);
       txt_name.setText(name);
       txt_mail.setText(emial);
       txt_pass.setText(pass);
       txt_address.setText(address);
       
      JOptionPane.showMessageDialog(null," the selected ID :"+id);
      
      
    }//GEN-LAST:event_table_viewMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_allview;
    private javax.swing.JButton btnclear;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnsearch;
    private javax.swing.JButton btnupdate;
    private javax.swing.JComboBox<String> cmbocourse;
    private com.toedter.calendar.JDateChooser date_chooser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblimg;
    private javax.swing.JRadioButton rd_female;
    private javax.swing.JRadioButton rd_male;
    private javax.swing.JRadioButton rd_other;
    private javax.swing.JTable table_view;
    private javax.swing.JTextArea txt_address;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_mail;
    private javax.swing.JTextField txt_name;
    private javax.swing.JPasswordField txt_pass;
    // End of variables declaration//GEN-END:variables
}
